### ISSUE TITLE
Feature to automatically `add_route` all operations from swagger_spec

### ISSUE THREAD

**Issue by prat0318** [striglia/pyramid_swagger#102]
Currently, the service-author has to manually do all the `add_route` even when it can be automatically be extracted from the `swagger_spec`. This will be a `opt-in` feature, default to `False`.

**Comment by dnephin** [comment]
I believe this is a duplicate of #3 which has some discussion about it

**Comment by prat0318** [comment]
yeah, should have searched the issues better. Closing it.
