### ISSUE TITLE
pyramid_swagger

### ISSUE THREAD

**Issue by sabrina261087** [striglia/pyramid_swagger#104]
Bonjour,
j'ai essayé de créer un projet pyramid en utilisant le tuto suivant: http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/project.html
Puis je voulais intégrer le pyramid_swagger en utilisant le lien suivant http://pyramid-swagger.readthedocs.org/en/latest/configuration.html

j'ai rien obtenu que des erreurs qui finissent pas

**Comment by sabrina261087** [comment]
Aide svp

**Comment by sabrina261087** [comment]
Hello,
I tried to create a pyramid project using the following tutorial: http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/project.html
Then I wanted to integrate pyramid_swagger using the following link http://pyramid-swagger.readthedocs.org/en/latest/configuration.html

I got errors

**Comment by sabrina261087** [comment]
"override this listing.".format(schema_dir, API_DOCS_FILENAME))
pyramid_swagger.ingest.ResourceListingGenerationError: C:/Users/sabrine/Desktop/
MyProjectSwagger/api_docs/api_docs.json has an `apis` listing. Generating a list
ing would override this listing.

**Comment by dnephin** [comment]
It sounds like you've set `pyramid_swagger.generate_resource_listing = true` , you can set it  to false and it will use your existing `api_docs.json`

**Comment by sabrina261087** [comment]
just for information , I modified only the file developement.ini 
and i keep _init_.py empty 

from pyramid.config import Configurator


def main(global_config, **settings):
    """ This function returns a Pyramid WSGI application.
    """
should I add these lines?
    settings['pyramid_swagger.schema_directory'] = 'C:/Users/sabrine/Desktop/MyProjectSwagger/api_docs'
    settings['pyramid_swagger.enable_swagger_spec_validation'] = True
    # ...and so on with the other settings...
    config = Configurator(settings=settings)
    config.include('pyramid_swagger')

**Comment by dnephin** [comment]
http://pyramid-swagger.readthedocs.org/en/latest/configuration.html is just an example showing you what options are available. You don't need to see anything except for `schema_directory` I think.

**Comment by sabrina261087** [comment]
so I should only add 
pyramid.includes = pyramid_swagger

# `api_docs.json` directory location.
# Default: 'api_docs/'
pyramid_swagger.schema_directory = 'api_docs/'
to developement.ini and I don't change the other files of my project?
concerning the json files , I created 2 files: api_docs.json which contains 
{
    "swaggerVersion": "1.2",
    "apiVersion": "1.0",
    "apis": [
       
        {
            "path": "/store"
        }
      
    ]
}

and store.json

**Comment by sabrina261087** [comment]
wainting for your response 
Thanks in advance

**Comment by sabrina261087** [comment]
I followed the steps and I create a new project . I got the error 

    'must be named {1}'.format(resource_listing, API_DOCS_FILENAME)
pyramid_swagger.ingest.ResourceListingNotFoundError: No resource listing found a
t "api_docs/"\api_docs.json. Note that your json file must be named api_docs.jso
n

**Comment by striglia** [comment]
Have you created a sample schema in that directory yet? You also might find the quickstart guide helpful http://pyramid-swagger.readthedocs.org/en/latest/quickstart.html

**Comment by sabrina261087** [comment]
this is my project
I don't know what's the problem

2015-04-29 18:14 GMT+02:00 Scott Triglia <notifications@github.com>:

**Comment by sabrina261087** [comment]
please I'm waiting  your help

2015-04-30 13:34 GMT+02:00 Sabrine Moumni <sabrina261087@gmail.com>:

**Comment by sabrina261087** [comment]
Hi,
how do u do? I HAVE A QUESTION

If it runs coorectly, it should generate a file swagger.json under the
api_docs folder?

2015-04-30 13:35 GMT+02:00 Sabrine Moumni <sabrina261087@gmail.com>:

**Comment by striglia** [comment]
Swagger files will never be generated automatically. The pyramid_swagger library assumes you have a fully accurate Swagger schema, and a Pyramid application which accurately implements all endpoints described in that schema. If you have not yet written a full Swagger schema, I'd suggest starting with that task (http://swagger.io/ is a good starting point). Once you are sure you have a valid Swagger schema *and* a Pyramid application that implements it, I'd be happy to help you get it running under pyramid_swagger.

**Comment by sabrina261087** [comment]
If i will develop the application , the hole application , what's the goal of pyramid_swagger?
whay should I integrate it?

**Comment by striglia** [comment]
The documentation summarizes pyramid_swagger's goals: http://pyramid-swagger.readthedocs.org/en/latest/. Mostly, we are focused on enforcing the accuracy of your Swagger schema against requests your application receives.

**Comment by striglia** [comment]
closed for lack of feedback
