### ISSUE TITLE
api_docs.json 

### ISSUE THREAD

**Issue by sabrina261087** [striglia/pyramid_swagger#105]
"override this listing.".format(schema_dir, API_DOCS_FILENAME))
pyramid_swagger.ingest.ResourceListingGenerationError: C:/Users/sabrine/Desktop/
MyProjectSwagger/api_docs/api_docs.json has an `apis` listing. Generating a list
ing would override this listing.

this error means that pyramid_swagger generates resourcelisting using api_docs.json ?
if it generates the resourcelisting, where can i find it? else how can I solve this problem

**Comment by striglia** [comment]
Can you include the full traceback you are getting, as well as the configuration options you are using? I'm not sure I fully understand the issue you are having yet.

**Comment by sabrina261087** [comment]
give me ur mail, I will send the hole project, really I feel dispointed to solve all these errors 

Here I will describe the steps :
1- I created a pyramid project using this tuto http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/project.html
2- I put the project pyramid_swagger under the main directory ( pyramid_swagger is downloaded from https://github.com/striglia/pyramid_swagger
3- I Modified the file developement.ini 
4- I created a folder api_docs which contains the json 2 files (api_docs.json and store.json)
5-  I run the project using command line 

I got the error 
    'must be named {1}'.format(resource_listing, API_DOCS_FILENAME)
pyramid_swagger.ingest.ResourceListingNotFoundError: No resource listing found a
t "api_docs/"\api_docs.json. Note that your json file must be named api_docs.jso
n

**Comment by striglia** [comment]
Can you paste the contents of store.json here?

Your error looks like pyramid_swagger cannot find your api_docs.json in the api_docs folder. Is the path `C:/Users/sabrine/Desktop/
MyProjectSwagger/api_docs/api_docs.json` correct and pointing to the actual file? What's the value of the `pyramid_swagger.schema_directory` configuration setting in your .ini?

**Comment by striglia** [comment]
closed for lack of feedback
