### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by dhekrazaied** [striglia/pyramid_swagger#106]
I set pyramid_swagger.schema_directory = /Users/ip-Label/Virtualenvs/foobar-py3/ini/api_docs

and I have the folder api_docs which contain my jsons like in ur example.

but always I get this error:
400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

Could not find the relevant path (/) in the Swagger schema. Perhaps you forgot to add it?

**Comment by striglia** [comment]
You will get 400 responses anytime you query for an endpoint not described in your schema. Are you querying an endpoint which does not exist in your schema?

**Comment by dhekrazaied** [comment]
Hi
when I edit mu api_docs.json like this 
{
    "swaggerVersion": "1.2",
    "apiVersion": "1.0",
    "basePath": "http://petstore.swagger.io/api",
    "apis": [
        {
            "path": "/pet"
        },
        {
            "path": "/store"
        },
        {
            "path": "/user"
        }
    ]
}
I have this error pyramid_swagger.ingest.ResourceListingGenerationError: api_docs/api_docs.json has an `apis` listing. Generating a listing would override this listing.
When I remove apis from api_docs.json I get this in the browser Could not find the relevant path (/) in the Swagger schema. Perhaps you forgot to add it?

How can fix that?

**Comment by dhekrazaied** [comment]
now I have this log in the browser
404 Not Found

The resource could not be found.

/pet/

**Comment by dhekrazaied** [comment]
Hi
When I add in the init.py this line
  config.add_route('hello', '/pet/')
 I get no error in the browser http://127.0.0.1:6543/pet/  but I have no result what I should I will get?

**Comment by dhekrazaied** [comment]
Should I have a local data base to add my pets?

**Comment by striglia** [comment]
Are you sure the application itself is running? I would encourage you to pick a simple endpoint to implement (not the whole Pet example from Swagger.io), implement it as a Pyramid application that you know works, and only then integrate it with pyramid_swagger. If you get through all that I'm happy to help you debug this library, but it sounds like you are asking for how to implement the application itself.

**Comment by sabrina261087** [comment]
what does it mean endpoint? 
file json? or what ?

**Comment by striglia** [comment]
By endpoint I mean a particular pyramid view (like GET on "/pet"). You can see my comment on #104 to see what the goals of pyramid_swagger are, but it definitely does not build your application for you or provide any database.

**Comment by striglia** [comment]
closed for lack of feedback
