### ISSUE TITLE
Data base pyramid swagger

### ISSUE THREAD

**Issue by sabrina261087** [striglia/pyramid_swagger#107]
Hi,
I'm using pyramid swagger in my project, I don't know where does it stock the data?
is there any data base?
for example If I want to create a new pet, or to get pets(' available' )using url http://localhost:6543/api_docs/pet/findByStatus?status=available, how can it provide data?

**Comment by dhekrazaied** [comment]
Same question.
Please can u answer us?

**Comment by striglia** [comment]
pyramid_swagger is a tool which mainly is used for validating your requests match your Swagger schema. You still must write your Pyramid application yourself. I'd encourage you to first write the application you want to implement, then integrate it with pyramid_swagger to get the free validation and other features.
