### ISSUE TITLE
error pyramid swagger 

### ISSUE THREAD

**Issue by sabrina261087** [striglia/pyramid_swagger#108]
http://localhost:6543/pet/findByStatus?status=available/

400 Bad Request

The server could not comply with the request since it is either malformed or otherwise incorrect.

'available/' is not one of ['available', 'pending', 'sold'] Failed validating 'enum' in schema['properties']['status']: {'allowMultiple': True, 'defaultValue': 'available', 'description': 'Status values that need to be considered for filter', 'enum': ['available', 'pending', 'sold'], 'name': 'status', 'paramType': 'query', 'required': True, 'type': 'string'} On instance['status']: 'available/'

**Comment by striglia** [comment]
The trailing slash is being included in your `status` query argument. If you remove it, this should work.

**Comment by sabrina261087** [comment]
No , it does not work 
I test it

**Comment by sabrina261087** [comment]
404 Not Found

The resource could not be found.

/pet/findByStatus

**Comment by striglia** [comment]
Without knowing more about your application, this will be very hard to debug. Does the application work *without* pyramid_swagger? It sounds like your application may not be functional, and this library only wraps an existing project that already works with some additional features like request validation.

**Comment by striglia** [comment]
closed for lack of feedback
