### ISSUE TITLE
JsonRef cannot be serialised via pyramid jsonrenderer

### ISSUE THREAD

**Issue by MartinPeschke** [striglia/pyramid_swagger#114]
so this 

http://stackoverflow.com/questions/27005105/swagger-use-ref-to-pass-a-reusable-defined-parameter

cannot be done and causes a 500 (unserializable).

No combination of added jsonRenderer will serialise this.

    jsonRenderer = JSON()
    def srls_json_ref(o, request):
         return dict(o)
    jsonRenderer.add_adapter(Proxy, srls_json_ref)
    jsonRenderer.add_adapter(JsonRef, srls_json_ref)

So I had to disable api-docs views and serve it as a static file

**Comment by striglia** [comment]
Hi Martin,

You seem to be attempting to use a feature unique to Swagger's 2.0 spec. As support for that is brand new to this library (in face, not even fully released yet), a bug internally is entirely possible.

Can you copy your Swagger schema into this issue, ideally as stripped down as is possible to still reproduce the issue? After we've got a reproduction, I think the solution may better present itself.

**Comment by striglia** [comment]
Lost to the sands of time ⏳
