### ISSUE TITLE
basePath gets ignored on route matching (bravado spec resources)

### ISSUE THREAD

**Issue by MartinPeschke** [striglia/pyramid_swagger#115]
version 2.0.0-rc1, used as a tween alongside pyramid_tm and debugtoolbar

validation will try to match the full route.path against only the path defined in the swagger-paths object.

I.e. in the example:

      "basePath": "/api",
      "paths": {"/pets": {"get": {} } }

I.e. in the loop in Baravado spec (https://github.com/Yelp/bravado-core/blob/master/bravado_core/spec.py#L119

It will not be able to find:

     key = (get, '/api/pets)

in _request_to_op_map, since that only contains

     { (get, '/pets'): .... }

**Comment by MartinPeschke** [comment]
this is a feature, isnt it?

**Comment by striglia** [comment]
I have not done much work with non-root basePaths myself, but I do believe that what you describe is correct (the validation should be done against the combination of the URI path portion of the basePath and the API object's path.

Did you close this issue because this feature works as intended?

**Comment by analogue** [comment]
This does indeed look like a bug. I'll get a PR with out with a fix shortly.

**Comment by analogue** [comment]
Released in pyramid-swagger-2.0.0-rc2
