### ISSUE TITLE
[v1.2] casting booleans always returns in True

### ISSUE THREAD

**Issue by dnephin** [striglia/pyramid_swagger#126]
https://github.com/striglia/pyramid_swagger/blob/swagger_12/pyramid_swagger/tween.py#L293

unfortunately casting string to boolean is not as simple as `bool()`

**Comment by striglia** [comment]
Shouldn't it just be bool(json.loads(value))? Are we not loading the json first?

**Comment by dnephin** [comment]
json bodies would already be casted by `json.loads()`, it's an issue for query/path/form I think

**Comment by striglia** [comment]
Looks like most people are effectively focusing on Swagger 2.0 at this point, so closing this 1.2 issue.
