### ISSUE TITLE
Support YAML specs for 2.0

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#134]
Pretty simple for pyramid_swagger. Need to get bravado-core to support it ([issue link](https://github.com/Yelp/bravado-core/issues/42)) and then update a small amount of code in pyramid_swagger to accept both json and yaml.

**Comment by djeebus** [comment]
As a heads up, I added yaml support (in Yelp/bravado-core#73) to bravado-core, and I'm working on adding yaml support to pyramid-swagger. Progress is being made! =)

**Comment by djeebus** [comment]
The branch is here if you're anxious to see what it looks like: https://github.com/djeebus/pyramid_swagger/tree/add-yaml-support

I'm waiting on bravado-core to release a new version that we can depend on in pyramid-swagger. *taps foot impatiently* =)

**Comment by analogue** [comment]
@djeebus bravado-core 4.1.0 is up on pypi now

**Comment by djeebus** [comment]
@analogue fantastic! =) Thanks, I'll get the yaml PR here soon.

**Comment by striglia** [comment]
Resolved by #156
