### ISSUE TITLE
Add config to be able to add separate schema dir for swagger.json

### ISSUE THREAD

**Issue by prat0318** [striglia/pyramid_swagger#137]
Right now, it has to be the same as `schema_dir` for v1.2 but should not be.

**Comment by striglia** [comment]
Is it equivalently easy to make the config option for 1.2 location? How do these interact if you only support 1.2 or 2.0? 

I'd prefer the "schema_dir" simply refer to 2.0 for pyramid_swagger > 2.0.0 if at all possible. We don't want to make the average user migrate to some non-backwards-compatible change if at all possible.

**Comment by striglia** [comment]
I'm going to close this in favor of just entirely removing 1.2 support from pyramid_swagger in version 3.0 of the library (see #174). I think migration is sufficiently possible in the existing versions, so I'm going to close this in the hopes that makes sense :)
