### ISSUE TITLE
RequestValidationError generates bad response

### ISSUE THREAD

**Issue by tholo** [striglia/pyramid_swagger#142]
If you get a RequestValidationError (mismatched path, whatever), the generated HTTP response is invalid. Specifically, it generates a:

```
HTTP/1.1 None None
```

response... This is due to RequestValidationError inheriting from `HTTPClientError` instead of e.g. `HTTPBadRequest`, and also does not set the status code and message.

I discovered this as I was tracking down a validation error (could not match a `"/api/v1/users/{userId}"` from swagger.json, using a `@resource(r'/users/{id:\d+}')` from Pyramid code ... had to remove the Pyramid-style expression. Which is safe with the request now being validated by Swagger. Plus I had to use the same identifier "userId" both places. Might be worth documenting.

**Comment by sjaensch** [comment]
I can't reproduce this issue, is this still happening for you @tholo?

**Comment by tholo** [comment]
No, this was apparently fixed in 28cc09b479dcd2ed179d60983bcdcbe32302c965
