### ISSUE TITLE
Dead links to bravado-core

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#144]
See the link to SwaggerFormat in http://pyramid-swagger.readthedocs.org/en/latest/configuration.html#user-formats-swagger-2-0-only. Is this object obsolete?

cc @prat0318

**Comment by prat0318** [comment]
No, it's not. spatel is making a PR to update pyramid-swagger to the new
bravado-core changes. But i think the external interface will remain the
same.

On Sunday, October 11, 2015, Scott Triglia <notifications@github.com> wrote:

> See the link to SwaggerFormat in
> http://pyramid-swagger.readthedocs.org/en/latest/configuration.html#user-formats-swagger-2-0-only.
> Is this object obsolete?
>
> cc @prat0318 <https://github.com/prat0318>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/striglia/pyramid_swagger/issues/144>.
>


-- 
Prateek Agarwal

**Comment by striglia** [comment]
Fixed in v2.2.2
