### ISSUE TITLE
Documentation is unclear how Swagger API calls are matched to Pyramid routes

### ISSUE THREAD

**Issue by miohtama** [striglia/pyramid_swagger#155]
It is unclear from documentation how Swagger paths are matched to Pyramid paths and how 
pyramid_swagger discovers the underlying API call

* Is there an explicit way to say "this view is this Swagger API call" or is it discovered implicitly

* Should or should not Swagger `basePath` somehow be handled by the user or is it handled automatically or should it be ignored

* Are paths from Swagger JSON absolute paths for routes in Pyramid or somehow relative to something

**Comment by striglia** [comment]
Thanks for the issue Mikko!

You're not the first person to be confused on this topic, so I think it's definitely worth shoring up in the documentation. In general, pyramid_swagger enforces validation on the endpoints described by your Swagger spec. 

Swagger just thinks in terms of HTTP methods + URLs, and pyramid_swagger ensures requests are checked against that spec before being handled by your Pyramid views. There is no explicit way to connect a view to a Swagger API call, but when you register a HTTP method+URL against a view, pyramid_swagger can then connect your spec to that view by matching against the method+URL.

As for the questions about basePath, I think that's best answered by the Swagger spec itself:

> A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended to the basePath in order to construct the full URL. Path templating is allowed.

So basePath is a prefix, and paths are appended onto the end of it. Useful if your entire API is served from something like `/StrigliaCorp/resource_1/` and `/StrigliaCorp/resource_2` and you don't want every path in your spec to start with `/StrigliaCorp`.


So all that said, I think the docs could use improvement on explaining how the routes described in the Swagger spec are registered against views. I think the existing [quickstart section](http://pyramid-swagger.readthedocs.org/en/latest/quickstart.html) is heavy on the step-by-step but probably fails to give the larger picture of how pyramid_swagger is working.

Does this all make sense? Any other feedback on what is confusing?

**Comment by miohtama** [comment]
I think I'll write some full examples when I figure out this.

I was thinking the only use case for basePath is versioning - did not think it could be used for something else (`v1`, `v2`, etc). A quick start only needs a sample Swagger JSON (Yaml preferred) and then matching Pyramid view with full story.

**Comment by striglia** [comment]
In the interest of cleanliness, I'm going to clean this up as a resolved issue. That said, I'd be happy to merge any PRs to improveme the docs :)
