### ISSUE TITLE
boolean values in .ini configuration don't work -- need conversion using paste.deploy.converters

### ISSUE THREAD

**Issue by deubs** [striglia/pyramid_swagger#182]
boolean settings, like this:
pyramid_swagger.enable_path_validation = False
are read as strings when configured via .ini file.
and are always True

**Comment by hugoduncan** [comment]
I think https://github.com/striglia/pyramid_swagger/blob/928f4d47613e16a4e63868a2bda916eb9118b190/pyramid_swagger/tween.py#L346 should use `paste.deploy.converters:asbool` to convert the values to booleans.

**Comment by striglia** [comment]
Ah perfect! I figured this must exist, but obviously was not aware of it 😄  Sounds like a totally fixable problem.
