### ISSUE TITLE
Swagger 2.0 validation errors don't raise RequestValidationError

### ISSUE THREAD

**Issue by ClareCat** [striglia/pyramid_swagger#195]
Here the validation_context is inside the validation_error decorated function so any raised issues aren't caught and made generic for handling by the validation context.

```python
@validation_error(RequestValidationError)
def swaggerize_request(request, op, **kwargs):
    validation_context = kwargs['validation_context']
    with validation_context(request):
        request_data = unmarshal_request(request, op)
    return request_data
```

**Comment by striglia** [comment]
The intent of the various uses of @validation_error was definitely to consolidate arbitrary underlying errors into a consistent, correct, and catchable exception class. This is a good example of some code that makes no sense, as `validation_context` is forced to know way too much about the underlying code to be effective.

As a side note, we should also make sure that `validation_error` is preserving the full child exception for inspection, in case that's important to anyone. I don't think we want to explicitly encourage that level of behavior, but I'm happy for expert users to rely on it, assuming they know it is brittle and not guaranteed.

**Comment by ClareCat** [comment]
Looking at the code this was the only place that did this incorrectly. I wasn't sure if it would be worth it to work this validation_context into the validation_error decorator, but it would reduce the possibility of this happening in the future.
