### ISSUE TITLE
Spec validation fails randomly (for 3.x only) on unresolvable json pointer to itemsObject.json

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#20]
Seems fairly concerning but I can't pin it down well. The only useful bit of diagnosis I can offer is this seems to happen only for parameterObjects that are of array type. In particular, this definitely has been reproduced with {type: array, items: {type: string}}, and can be reproduced by removing the @pytest.mark.skipif decorator on tests in the spec_validation_test module.

Happens (very roughly) on 10% of runs with no discernable pattern. Perhaps caused by jsonschema validation order affecting something?

For now, I'll forge ahead with spec validation with a warning against using it in 3.x, since all our current users are on 2.x.

**Comment by dnephin** [comment]
This will be fixed by https://github.com/Julian/jsonschema/pull/203

**Comment by striglia** [comment]
Fixed by upgrading jsonschema, and no longer using pyramid_swagger's jsonschemas to validate the Swagger specs.
