### ISSUE TITLE
swagger_versions doesn't work 

### ISSUE THREAD

**Issue by zhouxiaoxiang** [striglia/pyramid_swagger#200]
when use swagger_versions in ini:
`pyramid_swagger.swagger_versions = ['2.0'] `
will cause:
    Swagger version [ is not supported

pyramid_swagger/tween.py:
`swagger_versions need be converted to list.`

**Comment by sjaensch** [comment]
@zhouxiaoxiang are you sure that syntax is correct for INI files? Have you tried `pyramid_swagger.swagger_versions = 2.0`?

**Comment by striglia** [comment]
The INI format is definitely a strange one. I like http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html as my reference for how to encode various basic data types.

**Comment by sjaensch** [comment]
@zhouxiaoxiang our documentation is not correct in regards to the format of settings in the INI file, I'm fixing it in #189 - as well as making sure we read this particular setting correctly if you specify both swagger versions. Just to reiterate, `pyramid_swagger.swagger_versions = 2.0` should do what you want. You could also simply remove that line as that is the default.
