### ISSUE TITLE
Expose helper method for extracting bravado_core Operation object from pyramid request

### ISSUE THREAD

**Issue by macisamuele** [striglia/pyramid_swagger#212]
While implementing endpoints that accept enum value in parameters could be interesting to have a framework support for extracting Operation object from pyramid request object.

I have in mind 2 main use cases for this:
1. in writing tests to ensure that enum strings (swagger specs) will be properly converted to enum python objects
2. in input handling of list of enums in case the assumption "all enum values if nothing is passed to the parameter"

I can prepare a PR for this, let me know if you have strong opinion against this.

pinging: @striglia , @sjaensch

**Comment by striglia** [comment]
Can you clarify point 2 here? Point 1 is important, but can probably be accomplished without exposing these APIs formally. Are there use cases other than handling enum values?

**Comment by macisamuele** [comment]
I have no other use cases in mind.

I was mainly thinking to enum use case because while writing specs often
happen that we define parameters as list of enum values (especially for
optional filters).
When the parameter is not provided the most general handling of it is to be
considered equivalent to all the valid enum values.
Without a feature like that developers need to manually keep
synchronization between specs and python.

Do you have different ideas for a similar use case?

Il 30 ago 2017 7:53 PM, "Scott Triglia" <notifications@github.com> ha
scritto:

Can you clarify point 2 here? Point 1 is important, but can probably be
accomplished without exposing these APIs formally. Are there use cases
other than handling enum values?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/striglia/pyramid_swagger/issues/212#issuecomment-326069030>,
or mute the thread

**Comment by macisamuele** [comment]
@striglia I'm closing this issue because [``get_op_for_request``](https://github.com/striglia/pyramid_swagger/blob/1f5836520ebcb0f110b13b133fcee63330bc98e4/pyramid_swagger/tween.py#L591) already performs the needed operation

**Comment by striglia** [comment]
Cool, happy it works for you 👍
