### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by macisamuele** [striglia/pyramid_swagger#219]
Hello @striglia do you have plans to release the new pyramid_swagger version anytime soon?
I would like to start benefit of #214 and eventually #216 when the review process will be completed 😄

**Comment by striglia** [comment]
Once we have a few features you'd like out, you are very free to kick off a release yourself :) I've added you as an admin, and @sjaensch already is too so we should have plenty of coverage.

My normal process is just:
* bump the version in `pyramid_swagger/__about__.py`
* Make sure the changelog looks right (reflecting the new tag)
* Git tag the same version on the commit where I do the two previous things
* Push all that to master, tags included.
* Once travis passes, publish the sdist and bdist_wheel to pypi. Stephan also has permissions to do this and I'm happy to add you as well if you have a PyPI username and are interested 👍

**Comment by macisamuele** [comment]
@striglia thanks a lot for your support. I've created a pypi account, username is ``macisamuele``
About the new release it would be great to have #216 too 😄  (even if you gave me admin rights on the project I cannot approve my own PR, doesn't seems correct)

**Comment by striglia** [comment]
Cool, you're added on pypi as well, so either you or Stephan should be able
to update the package there.

I'll put #216 on my queue for today. Hopefully we're close and it won't
require too much more back and forth. Thanks for being patient!

**Comment by dimkonko** [comment]
@striglia Can you give an update about the status of the new release? I'm still desperately waiting for https://github.com/striglia/pyramid_swagger/pull/217 to be released.

**Comment by striglia** [comment]
@macisamuele you want to run this release so you get the chance? If you're busy lmk and I can take care of it. Figure we can release 2.5.0 w/ the above steps and get these features out there 🚢

**Comment by macisamuele** [comment]
@striglia sure

**Comment by macisamuele** [comment]
@dimkonko @striglia version 2.5.0 is available on pypi 🎉
