### ISSUE TITLE
Support formats on types

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#50]
e.g. date-time formatting. This is a semi-builtin feature of the jsonschema library, so it should be quite doable. See [this man entry](http://python-jsonschema.readthedocs.org/en/latest/validate/#validating-formats) for more information.

**Comment by dnephin** [comment]
I believe v2 comes with validation and casting of the build in formats (int, bool, datetime, date).

Another thing we can do is user defined formats. Swagger 2.0 actually allows for any string to be used as a format. If pyramid_swagger accepted a mapping of "format name -> validator function" it could use the function to validate and cast the value to the expected type.

I think it could accept that mapping from the pyramid registry `user_format_validators` maybe?

On the client side these formats would be purely documentation.

**Comment by prat0318** [comment]
- [pyramid_swagger] Get the registered validator functions and pass them to bravado
- [bravado] Somewhere [here](https://github.com/Yelp/bravado-core/blob/master/bravado_core/formatter.py#L51) check if format_name is available in registered validators. If yes, use it else ignore.
- [client side bravado] Ignore the format if not present in built-ins

**Comment by striglia** [comment]
@prat0318 @analogue is this fixed by the move to use bravado-core? Do we have any tests in place to ensure it works?

**Comment by prat0318** [comment]
Part of bravado-core is implemented. I have yet to send a PR for pyramid_swagger for integrating this part with bravado-core.
