### ISSUE TITLE
Response validation can be very slow

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#54]
Vague bug report here...in need of some more concrete examples and evidence.

Response validation was adding an addition ~150ms to our pyramid app's end-to-end timings. This seems downright silly, as nothing pyramid-swagger is doing should take that long. Should be possible to reproduce with a large response body and a schema involving a few nested models. This ticket should be made much more concrete before any action is taken.

**Comment by striglia** [comment]
Will this improve noticeably with your upstream changes in jsonschema?

**Comment by dnephin** [comment]
We should see significant improvements with that branch, yes

**Comment by striglia** [comment]
Do we believe this has improved enough to close out?

**Comment by dnephin** [comment]
Hopefully, but I don't have any numbers on it.  I also think there is very little that can really be done as part of `pyramid_swagger` to fix this. I'd be fine closing the issue.

**Comment by striglia** [comment]
Works for me. Thanks for digging into the jsonschema!
