### ISSUE TITLE
Make api-docs registration customizable

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#73]
Currently pyramid_swagger will register the api-docs/* endpoints automatically, with no opportunity for customization. There are several valid reasons to want to customize this (service of a different endpoint, authorization, etc.) and they should be exposed to users.

The implementation we decide on should ideally:
* Involve no configuration for users wanting the default behavior
* Allow those who need to customize full ability. Probably just delegate the entire registration process to them.

Worth noting that this will most likely end with us exposing (for the first time) our internal representation and access methods for the schemas to our users. Thar be dragons.

**Comment by dnephin** [comment]
Another use case for this would be to support both swagger 1.2 and 2.0 specs. We'd actually want to register two of these views with different paths.

I need this pretty soon, so I'll probably be working on it
