### ISSUE TITLE
Feature: Generate the resource listing

### ISSUE THREAD

**Issue by dnephin** [striglia/pyramid_swagger#83]
`pyramid_swagger.ingest.build_schema_mapping()` expects a file in a very specific format where the paths to api docs match the filename containing the docs (with the `.json` suffix removed). The rest of the listing file is pretty minimal (a `swaggerVersion` and an `apiVersion`). 

In another project I took the approach of generating this file instead. From the list of files in the directory (plus the two versions) we can create the entire resource listing. 

I propose we do the same in `pyramid_swagger` using `pyramid_swagger.generate_resource_listing` to enable the feature (default it to false for backwards compatibility).  The `apiVersion` and `swaggerVersion` could be specified in a file in the directory.

**Comment by striglia** [comment]
Hm. Is the argument here that the resource listing is completely uninteresting and should be done automatically? I guess if we can encode arbitrary resource names into filenames, this would be pretty easy. Or are you proposing pulling it from the resourcePath in the API Declaration?

**Comment by dnephin** [comment]
Ya, I think that's the idea. `pyramid_swagger` requires a very specific mapping between resource path and filename.  `/api-docs/resource` must be provided by a file at `<schema_dir>/resource.yaml`.

So instead of creating a file with all of those mappings, we could instead just `glob.glob('%s/*.yaml' % schema_dir)` to get the list of resources, and then build the resource listing from the base file (which can contain api versions and authentication I guess), and the `apis` section would be generated from the file list.

**Comment by sabrina261087** [comment]
I created a folder api_docs which contains 3 files : api_docs.json , pet.json and I added resource.yaml when I execute the command pserve development.ini , I got nothing , the file resource.yaml is empty , I got the error 
"override this listing.".format(schema_dir, API_DOCS_FILENAME))
pyramid_swagger.ingest.ResourceListingGenerationError: C:/Users/sabrine/Desktop/
MyProjectSwagger/api_docs/api_docs.json has an apis listing. Generating a list
ing would override this listing.

**Comment by striglia** [comment]
Hi Sabrina,

If your api_docs.json already has an `apis` entry, you'll want to make sure the configuration switch for resource generation is set to False: `pyramid_swagger.generate_resource_listing = false` in your `.ini` file.

**Comment by sabrina261087** [comment]
Hi,
I got a new error :'(
400 Bad RequestThe server could not comply with the request since it is
either malformed or otherwise incorrect.

Could not find the relevant path (/api_docs/pet) in the Swagger schema.
Perhaps you forgot to add it?

I verfied all the endpoints that exist under my folder /api_docs

2015-05-01 0:21 GMT+02:00 Scott Triglia <notifications@github.com>:

**Comment by sabrina261087** [comment]
If it runs coorectly, it should generate a file swagger.json under the
api_docs folder?

2015-05-04 9:55 GMT+02:00 Sabrine Moumni <sabrina261087@gmail.com>:

**Comment by striglia** [comment]
Let's have this discussion in a single issue (#104), so it's easier to keep track of.
