### ISSUE TITLE
Rich request validation beyond jsonschema

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#91]
We have had a few requests for allowing configuration in the Swagger spec of richer (logical) validation of request content. This would be things that either cannot be expressed in swagger or validation for which the application owner wants custom validation behavior (something more than just raising ValidationError).

In 1.2 this needs to be done solely within the pyramid_swagger configuration, as the spec itself allows no room for this. 

In 2.0 we should be able to utilize extensions to formalize an interface (maybe something like `X-Pyramid-Swagger-Custom-Validator: path.to.module:myvalidator_callable`)

**Comment by dnephin** [comment]
What's the word on this?

We have some rich validations build into swagger-py (but mostly bravado), and my feeling is these make a lot more sense on the server side.  We are planning on extracting this rich request/response validation into a shared package (maybe swagger_spec_validator?) so we can share them with pyramid_swagger.

I think that's one of the next steps for the swagger 2.0 project.

**Comment by striglia** [comment]
If you are talking about request (not swagger spec) validation, then yes this is that.

I'd be strongly in favor of having this solely be a pyramid_swagger feature, since it reduces surface area for out-of-library coupling and the interface will likely be assuming importable modules located server-side.

I am not sure I understand what kind of "rich validations" could be shared in client and server (and thus why they're appropriate for SSV). Examples?

**Comment by sabrina261087** [comment]
Hello,
I tried to create a pyramid project using the following tutorial: http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/project.html
Then I wanted to integrate pyramid_swagger using the following link http://pyramid-swagger.readthedocs.org/en/latest/configuration.html

I got errors

**Comment by sabrina261087** [comment]
"override this listing.".format(schema_dir, API_DOCS_FILENAME))
pyramid_swagger.ingest.ResourceListingGenerationError: C:/Users/sabrine/Desktop/
MyProjectSwagger/api_docs/api_docs.json has an `apis` listing. Generating a list
ing would override this listing.

**Comment by striglia** [comment]
Richer validation was added by #129 and the built-in extensions in Swagger 2.0
